/**
 * Cache for generated avatar sprites
 * 
 * This module provides a simple in-memory cache for generated
 * Dicebear avatar preview sprites to avoid regenerating them
 * on every render.
 * 
 * @module avatar/categories/spriteCache
 */

/**
 * In-memory cache for sprite data URIs
 * Key format: `${category}:${optionId}:${size}`
 */
const spriteCache = new Map<string, string>();

/**
 * Get a cached sprite if it exists
 * 
 * @param key - Cache key (generated by generateSpriteKey)
 * @returns Cached data URI or null if not found
 */
export function getCachedSprite(key: string): string | null {
  return spriteCache.get(key) || null;
}

/**
 * Store a sprite in the cache
 * 
 * @param key - Cache key (generated by generateSpriteKey)
 * @param dataUri - Data URI of the sprite to cache
 */
export function setCachedSprite(key: string, dataUri: string): void {
  spriteCache.set(key, dataUri);
}

/**
 * Generate a cache key for a sprite
 * 
 * @param category - Category of the option
 * @param optionId - ID of the option
 * @param size - Size of the sprite
 * @returns Cache key string
 */
export function generateSpriteKey(category: string, optionId: string, size: number): string {
  return `${category}:${optionId}:${size}`;
}

/**
 * Clear the entire sprite cache
 * Useful for memory management or when resetting
 */
export function clearSpriteCache(): void {
  spriteCache.clear();
}

/**
 * Get the current cache size
 * 
 * @returns Number of cached sprites
 */
export function getCacheSize(): number {
  return spriteCache.size;
}

