import { paintAndGuessHubEntry } from "@/games/paint-and-guess/hubEntry";
import type { GameRegistryPayload } from "./schema";

export const fallbackGameRegistry: GameRegistryPayload = {
  updatedAt: new Date().toISOString(),
  source: "fallback",
  entries: [
    {
      id: "paint-and-guess",
      name: "Paint & Guess",
      description: "Draw prompts, guess in real-time, and keep the momentum high for every round.",
      shortDescription: "Multiplayer drawing chaos",
      status: "available",
      route: "/games/paint-and-guess",
      thumbnail: "/placeholder.svg",
      featureFlag: "games.paintAndGuess",
      tags: ["featured", "multiplayer"],
      technologies: ["React", "Fabric.js", "Socket.io"],
      modes: ["party", "live-multiplayer"],
      players: { min: 2, max: 12 },
      estimatedDurationMinutes: 20,
      cta: { label: "Play now", to: "/games/paint-and-guess" },
      hub: paintAndGuessHubEntry,
    },
    {
      id: "mystery-mashup",
      name: "Mystery Mashup",
      description: "A rotating selection of prototypes for brave playtesters.",
      shortDescription: "Weekly experiments",
      status: "prototype",
      route: "#",
      thumbnail: "/placeholder.svg",
      featureFlag: "games.mysteryMashup",
      tags: ["prototype"],
      technologies: ["React"],
      modes: ["party"],
      players: { min: 3, max: 6 },
      estimatedDurationMinutes: 10,
      cta: { label: "Request access" },
    },
    {
      id: "trivia-trails",
      name: "Trivia Trails",
      description: "A branching trivia adventure with meaningful team choices.",
      shortDescription: "Choose-your-path trivia",
      status: "coming-soon",
      route: "#",
      thumbnail: "/placeholder.svg",
      featureFlag: "games.triviaTrails",
      tags: ["trivia", "co-op"],
      technologies: ["React"],
      modes: ["party", "coop"],
      players: { min: 1, max: 6 },
      estimatedDurationMinutes: 25,
      cta: { label: "Notify me" },
    },
  ],
};

